### ISSUE TITLE
万能的up大佬，帮忙看一下这个错吧，谢谢

### ISSUE THREAD

**Issue by eivaltsec** [Sg4Dylan/ncnn-webassembly-ocrlite#1]
![image](https://user-images.githubusercontent.com/6211195/124946842-eedeb180-e041-11eb-8e2e-e48c9456a2a0.png)
如上图，make的时候报错，【wasm-ld: error: unknown file type: alloc.cpp.o】，可能是什么原因呢？非常感谢，opencv我是先解压opencv-3.4.13-staticLib_3.7z，然后把opencv-mobile webassembly 3.4.13中basic目录下的文件copy到上一步解压的opencv目录中，然后再按照readme中目录层次调整的名称。

**Comment by Sg4Dylan** [comment]
这个是链接错误。
可能是在 WebAssembly 的编译阶段错误设置了目标平台为 x86/x86_64，而 OpenCV 和其他 EMSDK 并未使用这些目标平台编译。

**Comment by webstorage119** [comment]
Me too. I had same problem.
Would you give me solution?

**Comment by webstorage119** [comment]
I resolved problem. I missed to copy file in opencv_static. Thank you.
